In [1]:
import dicom
import numpy as np
from stl import mesh
import plotly.offline as py

import plotly.graph_objs as go
py.offline.init_notebook_mode(connected=True)

In [3]:
plan = dicom.read_file("rp.zordan.dcm")
print plan.BeamSequence[0].BlockSequence[0].BlockName

PERSO


In [4]:
print len(plan.BeamSequence[0].BlockSequence[0].BlockData)
print 
bdata= [float(val) for val in plan.BeamSequence[0].BlockSequence[0].BlockData]
x=[]
y=[]

for i in np.arange(0, len(bdata)):
    if i %2  ==0:
        x.append(bdata[i])
    else: 
        y.append(bdata[i])
#print x
print 
#print y

1316




In [5]:
trace1 = go.Scatter(
    x = x,
    y = y,
    mode = 'lines', 
    name = 'Block edge', 
    )
data1 = [trace1]
fig1= go.Figure(data=data1)   
py.iplot(fig1) 

# STL TOP 

In [7]:
pts_up=[]
for val in x:
    pt=[]
    pt.append(val)
    pt.append(y[x.index(val)])
    pt.append(0)
    pts_up.append(pt)
    
origin1=[0, 0, 0]

stl_top=[]
for i in range(0, len(pts_up)):
    f=[]
    z=i+1
    f.append(pts_up[i])
    if z > len(pts_up)-1: 
        f.append(pts_up[0])
    else:
        f.append(pts_up[z])
    f.append(origin1)
    stl_top.append(f)        
print(stl_top)

[[[23.0, 75.03515625, 0], [24.0, 75.089928057554, 0], [0, 0, 0]], [[24.0, 75.089928057554, 0], [25.0, 75.1404109589041, 0], [0, 0, 0]], [[25.0, 75.1404109589041, 0], [26.0, 75.1903225806452, 0], [0, 0, 0]], [[26.0, 75.1903225806452, 0], [27.0, 75.2425149700599, 0], [0, 0, 0]], [[27.0, 75.2425149700599, 0], [28.0, 75.2972222222222, 0], [0, 0, 0]], [[28.0, 75.2972222222222, 0], [29.0, 75.3461538461539, 0], [0, 0, 0]], [[29.0, 75.3461538461539, 0], [30.0, 75.3985849056604, 0], [0, 0, 0]], [[30.0, 75.3985849056604, 0], [31.0, 75.4504310344828, 0], [0, 0, 0]], [[31.0, 75.4504310344828, 0], [32.0, 75.4659574468085, 0], [0, 0, 0]], [[32.0, 75.4659574468085, 0], [33.0, 75.3494897959184, 0], [0, 0, 0]], [[33.0, 75.3494897959184, 0], [34.0, 75.234756097561, 0], [0, 0, 0]], [[34.0, 75.234756097561, 0], [35.0, 75.1223776223776, 0], [0, 0, 0]], [[35.0, 75.1223776223776, 0], [36.0, 75.00390625, 0], [0, 0, 0]], [[36.0, 75.00390625, 0], [36.03125, 75.0, 0], [0, 0, 0]], [[36.03125, 75.0, 0], [37.0, 74.

# STL BOTTOM

In [8]:
pts_down=[]
for val in x:
    pt=[]
    pt.append(val)
    pt.append(y[x.index(val)])
    pt.append(-20)
    pts_down.append(pt)
origin2=[0, 0, -20] 
stl_bot=[]
for i in range(0, len(pts_down)):
    f=[]
    z=i+1
    f.append(pts_down[i])
    if z > len(pts_down)-1: 
        f.append(pts_up[0])
    else:
        f.append(pts_down[z])
    f.append(origin2)
    stl_bot.append(f)
#print stl_bot

# STL SIDE

In [2]:
# Define the 8 vertices of the cube 
vertices = np.array([\
    [-125, -125, -7.5],
    [+125, -125, -7.5],
    [+125, +125, -7.5],
    [-125, +125, -7.5],
    [-125, -125, +7.5],
    [+125, -125, +7.5],
    [+125, +125, +7.5],
    [-125, +125, +7.5]])
# Define the 12 triangles composing the cube
faces = np.array([\
    [0,3,1],
    [1,3,2],
    [0,4,7],
    [0,7,3],
    [4,5,6],
    [4,6,7],
    [5,1,2],
    [5,2,6],
    [2,3,6],
    [3,7,6],
    [0,1,5],
    [0,5,4]])

# Create the mesh
cube = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
        cube.vectors[i][j] = vertices[f[j],:]

# Write the mesh to file "cube.stl"
cube.save('appli.stl')
print vertices
print faces
print cube[0]
print cube.vectors[0]

[[-125.  -125.    -7.5]
 [ 125.  -125.    -7.5]
 [ 125.   125.    -7.5]
 [-125.   125.    -7.5]
 [-125.  -125.     7.5]
 [ 125.  -125.     7.5]
 [ 125.   125.     7.5]
 [-125.   125.     7.5]]
[[0 3 1]
 [1 3 2]
 [0 4 7]
 [0 7 3]
 [4 5 6]
 [4 6 7]
 [5 1 2]
 [5 2 6]
 [2 3 6]
 [3 7 6]
 [0 1 5]
 [0 5 4]]
[-125.  -125.    -7.5 -125.   125.    -7.5  125.  -125.    -7.5]
[[-125.  -125.    -7.5]
 [-125.   125.    -7.5]
 [ 125.  -125.    -7.5]]


In [126]:
#test
# Create the mesh
cube = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
print cube[0]
print vertices.shape
for i, f in enumerate(faces):
#     print ' -> ', i
    print f
    for j in range(3):
#         print j
#         print vertices[f[j],:]
        cube.vectors[i][j] = vertices[f[j],:]
print cube[0]
print cube.vectors[0]
# Write the mesh to file "cube.stl"
cube.save('cube.stl')


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
(8, 3)
[0 3 1]
[1 3 2]
[0 4 7]
[0 7 3]
[4 5 6]
[4 6 7]
[5 1 2]
[5 2 6]
[2 3 6]
[3 7 6]
[0 1 5]
[0 5 4]
[-1. -1. -1. -1.  1. -1.  1. -1. -1.]
[[-1. -1. -1.]
 [-1.  1. -1.]
 [ 1. -1. -1.]]


In [10]:
#define vertices of 1 triangle of stl sup
vertices = np.array([\
    [9.5, 17.6826923076923, 0],
    [10.5, 17.871921182266, 0],
    [0, 0, 0],
    [10.5, 17.871921182266, 0],
    [11.5, 18.0616740088106, 0],
    [0, 0, 0]])
#define point to use
faces = np.array([\
    [0,1,2],
    [3,4,5]])
                      
   # Create the mesh
cube = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
        cube.vectors[i][j] = vertices[f[j],:]

# Write the mesh to file "cube.stl"
cube.save('tri2.stl')
print type(vertices)


<type 'numpy.ndarray'>


In [11]:
#define vertices of 1 triangle of stl sup
vertices2 = np.array([stl_top])

vertices2.resize((len(stl_top)*3,3))
print len(vertices2)
print vertices2[0]
print vertices2[0][1]


faces2=np.zeros((len(stl_top),3))
n=0
for i in range(0, len(stl_top)):
    n=(i*3)
    faces2[i]=[n, n+1, n+2]
#print len(faces2)
#print faces2

1974
[ 23.          75.03515625   0.        ]
75.03515625


In [98]:
test = mesh.Mesh(np.zeros(faces2.shape[0], dtype=mesh.Mesh.dtype))
print test[0]



[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [182]:
test = mesh.Mesh(np.zeros(faces2.shape[0], dtype=mesh.Mesh.dtype))
# print test[0]

for i in range(0, len(faces2)):
    print ' -> ', i
#     print f
    for j in range(3):
        print 'j : ' ,j
        print 'n : ', n
        n=(i*3)+j
        test.vectors[i][j] = vertices2[n][j]

# Write the mesh to file "cube.stl"
print vertices2[0:3]
print faces2[0]
print test[0]
print test.vectors[0]
test.save('tri6.stl')


 ->  0
j :  0
n :  195
j :  1
n :  0
j :  2
n :  1
 ->  1
j :  0
n :  2
j :  1
n :  3
j :  2
n :  4
 ->  2
j :  0
n :  5
j :  1
n :  6
j :  2
n :  7
 ->  3
j :  0
n :  8
j :  1
n :  9
j :  2
n :  10
 ->  4
j :  0
n :  11
j :  1
n :  12
j :  2
n :  13
 ->  5
j :  0
n :  14
j :  1
n :  15
j :  2
n :  16
 ->  6
j :  0
n :  17
j :  1
n :  18
j :  2
n :  19
 ->  7
j :  0
n :  20
j :  1
n :  21
j :  2
n :  22
 ->  8
j :  0
n :  23
j :  1
n :  24
j :  2
n :  25
 ->  9
j :  0
n :  26
j :  1
n :  27
j :  2
n :  28
 ->  10
j :  0
n :  29
j :  1
n :  30
j :  2
n :  31
 ->  11
j :  0
n :  32
j :  1
n :  33
j :  2
n :  34
 ->  12
j :  0
n :  35
j :  1
n :  36
j :  2
n :  37
 ->  13
j :  0
n :  38
j :  1
n :  39
j :  2
n :  40
 ->  14
j :  0
n :  41
j :  1
n :  42
j :  2
n :  43
 ->  15
j :  0
n :  44
j :  1
n :  45
j :  2
n :  46
 ->  16
j :  0
n :  47
j :  1
n :  48
j :  2
n :  49
 ->  17
j :  0
n :  50
j :  1
n :  51
j :  2
n :  52
 ->  18
j :  0
n :  53
j :  1
n :  54
j :  2
n :  55
 ->  19
j : 

IndexError: index 194 is out of bounds for axis 0 with size 194

In [183]:
print vertices2[0]
print faces2.shape[0]

test = mesh.Mesh(np.zeros(faces2.shape[0], dtype=mesh.Mesh.dtype))
print test.vectors[0]

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
194
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
